<%
Dim Top_BoardTop_UpdateTime
Top_BoardTop_UpdateTime = "2013/2/25 15:43:16"

Sub Top_BoardTop_View

%>
	<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table_in">
	<tr class=tbinhead>
		<td wdith=8% ><div class=value>&nbsp;</div></td>
		<td width=77% ><div class=value>版面</div></td>
		<td wdith=15% ><div class=value>发帖</div></td>
	</tr>
	<tr>
		<td class=tdbox>1</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=200>LeadBBS专区</a></td>
		<td class=tdbox>513155</td>
		</tr>	<tr>
		<td class=tdbox>2</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=230>ASP讨论区</a></td>
		<td class=tdbox>481102</td>
		</tr>	<tr>
		<td class=tdbox>3</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=333>开心灌水</a></td>
		<td class=tdbox>355116</td>
		</tr>	<tr>
		<td class=tdbox>4</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=10>风格美化</a></td>
		<td class=tdbox>288263</td>
		</tr>	<tr>
		<td class=tdbox>5</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=125>贴图漫画</a></td>
		<td class=tdbox>110535</td>
		</tr>	<tr>
		<td class=tdbox>6</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=100>雷霆二</a></td>
		<td class=tdbox>80982</td>
		</tr>	<tr>
		<td class=tdbox>7</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=2200>情人岛</a></td>
		<td class=tdbox>78550</td>
		</tr>	<tr>
		<td class=tdbox>8</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=2>站长交流</a></td>
		<td class=tdbox>65285</td>
		</tr>	<tr>
		<td class=tdbox>9</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=8>插件和增强</a></td>
		<td class=tdbox>55698</td>
		</tr>	<tr>
		<td class=tdbox>10</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=120>谈天说地</a></td>
		<td class=tdbox>52185</td>
		</tr>	<tr>
		<td class=tdbox>11</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=205>dotNet技术</a></td>
		<td class=tdbox>24884</td>
		</tr>	<tr>
		<td class=tdbox>12</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=210>其它源代码</a></td>
		<td class=tdbox>24128</td>
		</tr>	<tr>
		<td class=tdbox>13</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=260>电脑爱好者</a></td>
		<td class=tdbox>21400</td>
		</tr>	<tr>
		<td class=tdbox>14</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=115>音乐无限</a></td>
		<td class=tdbox>18815</td>
		</tr>	<tr>
		<td class=tdbox>15</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=900>论坛建议区</a></td>
		<td class=tdbox>17512</td>
		</tr>	<tr>
		<td class=tdbox>16</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=950>版主交流区</a></td>
		<td class=tdbox>12528</td>
		</tr>	<tr>
		<td class=tdbox>17</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=119>影视地带</a></td>
		<td class=tdbox>7233</td>
		</tr>	<tr>
		<td class=tdbox>18</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=300>八十年代</a></td>
		<td class=tdbox>7043</td>
		</tr>	<tr>
		<td class=tdbox>19</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=400>体育专区</a></td>
		<td class=tdbox>6838</td>
		</tr>	<tr>
		<td class=tdbox>20</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=220>技术精华区</a></td>
		<td class=tdbox>6528</td>
		</tr>	<tr>
		<td class=tdbox>21</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=222>JAVA技术</a></td>
		<td class=tdbox>5598</td>
		</tr>	<tr>
		<td class=tdbox>22</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=270>服务器技术/网络安全</a></td>
		<td class=tdbox>4709</td>
		</tr>	<tr>
		<td class=tdbox>23</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=212>PHP学习</a></td>
		<td class=tdbox>3796</td>
		</tr>	<tr>
		<td class=tdbox>24</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=520>专业服务区</a></td>
		<td class=tdbox>3259</td>
		</tr>	<tr>
		<td class=tdbox>25</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=30>模板美化</a></td>
		<td class=tdbox>2639</td>
		</tr>	<tr>
		<td class=tdbox>26</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=208>LeadBBS空间</a></td>
		<td class=tdbox>1931</td>
		</tr>	<tr>
		<td class=tdbox>27</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=116>LeadBBS电台</a></td>
		<td class=tdbox>1083</td>
		</tr>	<tr>
		<td class=tdbox>28</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=110>雷霆像册</a></td>
		<td class=tdbox>772</td>
		</tr>	<tr>
		<td class=tdbox>29</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=925>网站公告区</a></td>
		<td class=tdbox>638</td>
		</tr>	<tr>
		<td class=tdbox>30</td>
		<td class=tdbox>
			<a href=../b/b.asp?b=117>极速找歌</a></td>
		<td class=tdbox>451</td>
		</tr>	</table>
<%

End Sub
%>
